- .stylelintrc
style lint 규칙 완화
속성 순서에 어긋나도 괜찮도록 규칙을 완화했습니다.
[css 컨벤션](https://github.com/linkarchive/Front-End/wiki/css-%EC%BB%A8%EB%B2%A4%EC%85%98) 정리했습니다.
> chore: update style-lint configure flexible

- package.json
- src/pages/_app.tsx
- src/pages/reduxExample/index.tsx
- src/store/index.ts
- src/store/reducer.ts
- src/store/slices/exampleSlice.ts
리덕스 기본 환경 세팅
close #34 
- 라이브러리 설치
- store 생성
- rootReducer 생성
- _app에 사용 가능하도록 wrapper
- 예시 slice 생성
/reduxExample 로 이동하면 테스트 가능해요
> [feat] 리덕스 기본 환경 세팅

- .stylelintrc
- src/styles/GlobalStyle.ts
- css 변수를 사용할 수 있도록 스타일 린트 규칙 추가
- 오타 수정
#8
> Fix/global style.ts

- src/components/GoBackBtn.tsx
- src/components/Header.tsx
- src/styles/GlobalStyle.ts
- src/styles/globals.css
import 경로 수정했습니다.
- import 경로 수정
- 헤더 레이아웃 추가
- syltelint에 따라 global.css 변수명 수정
> [Fix] header 컴포넌트 compile 에러 수정

- package.json
- src/pages/_app.tsx
- src/styles/theme.ts
서버 상태 관리를 위한 react-query 설치
- close #41 
- react-query 설치
- react-query 초기설정
> [Feat] react-query 설치

- src/api/API.ts
- src/components/Create/HashTagList.tsx
- src/components/HashTag.tsx
- src/components/Input/index.tsx
- src/pages/create/index.tsx
- API 통신 작업 제외하고 폼 입력 검증 구현 작업했습니다.
- #33 
- react-query를 적용하여 요청 보내는 작업까지 했습니다만, 실제 api 통신 확인이 필요합니다. (작업예정)
- 해시태그와 레이아웃 디자인 개선이 필요합니다. (작업예정)
ps. 커밋이 너무 많아졌네요 😅 커밋 수가 10개가 되지 않도록 조절히겠습니다
> [FEAT] 링크 추가 기능 구현

- src/api/customAPI.ts
customAPI의 반복되는 부분을 함수로 분리했어요
close #55
> [feat] customAPI 반복되는 부분 제거

- src/api/customAPI.ts
- src/store/thunk.ts
프로덕션환경에서는 devtools가 안보이도록 수정
close #69 
master브랜치에 병합되면 프로덕션환경에서는 devtools가 안찍힐 거에요
> [fix] 개발환경에서만 devtools가 보이도록 설정

- src/api/API.ts
- src/api/customAPI.ts
- src/pages/auth/kakao/index.tsx
- src/store/thunk.ts
- src/utils/index.ts
authInstance에 토큰이 없어서 추가해야해요
close #71
> [fix] add token in instance

- src/pages/_app.tsx
- src/store/index.ts
터미널에서 레거시 경고발생
_app에서 코드를 조금 수정함
> [fix] 리덕스 레거시 제거

- next.config.js
- src/api/API.ts
- src/hooks/useImage.ts
- src/pages/user/[id].tsx
> [fix] 프로필 페이지 SSR -> CSR 변경

- src/components/LinkItem/LinkItem.type.ts
- src/components/LinkItem/LinkItemWithProfile.tsx
- src/components/LinkItem/TagLabelList.tsx
- src/components/LinkItem/index.tsx
> [fix] 링크 아이템 타입 수정

- src/api/API.ts
- src/components/LinkItem/LinkInfo.tsx
- src/components/LinkItem/LinkItem.type.ts
- src/pages/create/index.tsx
링크 추가 api 연동했습니다.
- #80 
- 프로퍼티명 수정
- 링크 불러오기시 meta title 값이 없는 경우 title 값 할당
> [Feat] 링크 추가 api 연동

- src/constants/index.ts
- src/middleware.ts
- src/pages/settings/profile/setnickname.tsx
향후 유지보수에 용이하도록 미들웨어 가독성을 개선해보았습니다.
검토하시고 코멘트 달아주시면 감사하겠습니다 🙇‍♀️
- 조건의 최초 분기점을 로그인 상태로 수정
- 비로그인 사용자는 `/login`, `/archive`, `/[nickname]` 만 접근 가능
- `config` 경로 수정
> [Refactor] 미들웨어 코드 가독성 개선

- src/_error.tsx
- src/pages/404.tsx
우리 서비스만의 에러 페이지 만들기
모든 방문마다 서버에서 에러페이지를 랜더링하는건 부하가 많아지고 느려지기 때문에
404는 정적페이지로 빌드 타임때 만들어져요
그 외의 에러는 _error.tsx에서 처리해요
close #119
> feat: create custom error pages

- src/api/API.ts
- src/components/LinkItem/LinkItem.type.ts
- src/components/LinkItem/LinkItemLits.tsx
- src/components/LinkItem/index.tsx
- src/hooks/useAuth.ts
- src/hooks/useToggleMark.ts
- src/pages/[nickname]/index.tsx
- src/pages/archive/index.tsx
- src/pages/index.tsx
- src/pages/mark.tsx
마크 기능
- 로그인 사용자만 북마크 기능을 사용하도록  로그인 상태를 확인하는 `useAuth` 훅을 만들었습니다. 
- 네트워크 비용을 줄이기 위해 [optimistic-updates](https://tanstack.com/query/v4/docs/react/guides/optimistic-updates) 를 사용해 `isMark`, `markCount`값을 업데이트 했습니다. 
close #117
> [Feat] 마크 기능

- src/api/API.ts
- src/pages/create/index.tsx
링크 불러오기시 한번만 수행되는 버그를 수정했습니다.
-  불러오기 버튼을 클릭시마다 패치할 수 있도록 `useQuery`가 아닌 `useMutation`훅으로 변경했습니다.
- https://github.com/linkarchive/Front-End/issues/80#issuecomment-1562487141
> [fix] 링크 불러오기 한번만 수행되는 버그 수정

- src/components/LinkItem/LinkItemWithProfile.tsx
- src/components/LinkItem/index.tsx
- src/pages/[nickname]/index.tsx
- src/pages/archive/index.tsx
- src/pages/settings/profile/index.tsx
- src/pages/settings/profile/setnickname.tsx
UI개선과 작은 버그 개선
close #125
close #126
> [fix] UI 개선, query에 item추가

- src/pages/create/index.tsx
> [fix] 링크 추가 안되는 버그 수정

- src/pages/mark.tsx
> [fix] 마크 페이지에서 새로고침시 api호출 안되는 버그

- src/store/slices/routerSlice.ts
> [fix] 로그인 헤더 네임 변경

- src/pages/auth/kakao/index.tsx
회의 후 로그인 성공 -> 둘러보기로 렌딩 페이지 변경
close #140
> [fix] 로그인 후 둘러보기 페이지로 이동

- src/pages/settings/profile/index.tsx
사용자 경험을 위해서 수정 완료시 메세지 보내기
close #131
> [feat] 프로필 수정시 토스트 메세지

- src/pages/settings/profile/index.tsx
> [feat] 사용가능한 이미지 파일 확장자 추가

- src/api/API.ts
- src/components/Create/FavoriteTagList.tsx
- src/pages/create/index.tsx
사용자의 자주 사용하는 해시태그 리스트(최대 10개)가 보여집니다
- 해시태그를 클릭하면 해시태그가 등록
- #176
close #176
> [Feat] 자주 사용하는 태그

- src/api/API.ts
- src/api/customAPI.ts
- src/pages/[nickname]/index.tsx
- src/pages/archive/index.tsx
백앤드에서 분기처리한 코드 하나로 합치는 api생성 -> 프론트도 따라서 api수정
close #183
> [FIX] 비로그인/로그인 분기처리한 코드 하나로 합치기

- README.md
- package-lock.json
- package.json
> [FEAT] README 작성

- __test__/Profile.test.tsx
- src/api/API.ts
- src/pages/settings/profile/index.tsx
- src/utils/cancelToken.ts
프로필 페이지 테스트 코드 개선을 위해서 코드를 수정했어요
close #195 
개발일지 : https://1yoouoo.tistory.com/34
> [TEST] 프로필 페이지 test 코드 수정

- src/pages/settings/profile/index.tsx
> [HOTFIX] 비동기 방어코드 추가

- src/api/API.ts
- src/components/Common/InfinityScroll.tsx
- src/components/LinkItem/DeleteButton.tsx
- src/components/LinkItem/LinkItemLits.tsx
- src/hooks/useInfinityScroll.ts
- src/pages/[nickname]/index.tsx
- src/pages/archive/index.tsx
- src/pages/index.tsx
- src/pages/settings/index.tsx
- src/pages/settings/trash/index.tsx
- src/store/slices/routerSlice.ts
- #200 
- #200 
- 무한 스크롤 컴포넌트 추출
- 임시 삭제 페이지 생성
- 임시 삭제 버튼 추가
> [FEAT] 링크 아이템 삭제 기능 

- public/assets/svg/chevron-left.svg
- src/api/API.ts
- src/components/Archive/Follower/Follower.type.ts
- src/components/Archive/Follower/FollowerList.tsx
- src/components/Common/Header/GoBackBtn.tsx
- src/components/Common/Header/Header.tsx
- src/components/Header/Header.tsx
- src/hooks/useFollowerTabs.tsx
- src/layouts/MainLayout.tsx
- src/pages/[nickname]/follower/index.tsx
- src/pages/_app.tsx
- 팔로워 리스트 api 연동
- fullPageLayout 추가
- #206 
- #221 
- #207
close #207
닉네임과 userId는 하드코딩 되어있습니당
팔로워 페이지에서는 `BottomNav`가 보이지 않도록 fullPageLayout을 추가했습니다
> [Feat] follower list

- src/api/API.ts
- src/components/Archive/Follower/FollowerList.tsx
- src/components/Archive/NicknameModal.tsx
- src/components/Archive/User/Button.tsx
- src/components/Archive/User/Profile.tsx
- src/components/Archive/User/User.type.ts
- src/components/HashTag/ReadOnly/HashTag.tsx
- src/components/HashTag/ReadOnly/HashTagList.tsx
- src/components/LinkItem/LinkItemWithProfile.tsx
- src/components/Settings/FavoriteTagList/index.tsx
- src/layouts/ProfileLayout.tsx
- src/lib/withAuth.ts
- src/pages/[nickname]/follower/index.tsx
- src/pages/[nickname]/index.tsx
- src/pages/archive/index.tsx
- src/pages/create/index.tsx
- src/pages/index.tsx
- src/pages/settings/hashtag/index.tsx
- src/pages/settings/index.tsx
- src/queries/index.ts
- src/store/slices/hashTagSlice.ts
- src/store/slices/userSlice.ts
nickname을 pk로 사용했는데 팔로우 기능추가시 이슈로 userId로 변경했어요
close #202
> [FIX] 기존 pk인 nickname을 userId로 전환

- src/components/Archive/Follower/FollowerList.tsx
- src/components/Archive/User/Profile.tsx
- src/components/ToastBar/index.tsx
- src/hooks/useToastBar.tsx
- src/layouts/System.tsx
- src/pages/create/index.tsx
- src/pages/settings/profile/index.tsx
- https://github.com/linkarchive/Front-End/issues/208
- #250
- 토스트바 피그마 디자인 반영했습니다.
- `useToastBar` 훅으로 좀 더 사용하기 편하도록 리팩토링 했습니다.
close #208
close #250
> [Refactor] toast bar 리팩토링 및 디자인

- __test__/Login/Login.test.tsx
- src/pages/login/index.tsx
- 로그인하지 않고 이용 하는 버튼 추가
- 화살표 없애기
close #224
> [FIX] 로그인 페이지 디자인 변경

- src/components/BottomNav/CreateBtn.tsx
- src/components/Home/SpeechBubbles/SpeechBubbles.tsx
- src/components/Home/Suggestion/Suggestion.tsx
- src/components/LinkItem/LinkItemList.tsx
- src/components/svg/Svg.tsx
- src/layouts/LinkItemLayout.tsx
- src/layouts/MainLayout.tsx
- src/middleware.ts
- src/pages/[nickname]/index.tsx
- src/pages/archive/index.tsx
- src/pages/feed/index.tsx
- src/pages/index.tsx
- src/store/index.ts
- src/store/reducer.ts
- src/store/slices/countSlice.ts
- src/store/slices/hashTagSlice.ts
- src/styles/globals.css
사용자의 링크가 없을 때 혹은 마크가 없을 때 페이지에 적힐 안내글자를 구현했어요
close #257
> [FEAT] 내 링크가 없을 때 안내 글자 구현

- src/pages/settings/hashtag/index.tsx
태그 등록 후 바로 반영이 안되는 문제를 해결했어요
close #271
> [FIX] 태그 수정시 자주 사용하는 태그에 바로 반영

- src/components/LinkItem/LinkItemList.tsx
- src/hooks/useInfinityScroll.ts
- src/layouts/LinkItemLayout.tsx
- src/store/slices/countSlice.ts
마크/언마크 후 바로 적용이 안되는 부분 해결했어요
close #269
> [FIX] 마크/언마크 후 바로 적용
